---
title: "Calibrated_Data_Filtering_And_Aggregation_By_Peptidoform"
output: html_document
date: "2023-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# set wd to parent folder
wd <- "C:/Users/jtzve/Desktop/Sufo_Tyrosine/01_Sulfotyrosine_Data_Processing/"
knitr::opts_knit$set(root.dir = wd)
```


```{r calibrated_data_readin}
# specify the extension unique to your calibrated files
extension = "thresholded_calibrated.tsv"
batch = "batch2_9"
# get all calibrated files
calibrated_files <- list.files(paste0(wd, batch), pattern = extension, full.names = TRUE, recursive = TRUE)
# extract the folder paths for hist plot f-n
folders <- dirname(calibrated_files)
# and the filenames for input in plot histograms f-n by Andy
input_filenames <- basename(calibrated_files)
# input_filenames <- input_filenames[16]
# read in all data one by one into an empty list, setting each data frame as a
# new elemnt of the list. 
calibrated_data <- list()
print("reading in data")
for (i in 1:length(calibrated_files)) {
  print(calibrated_files[[i]])
  calibrated_data[[i]] <- read.csv(calibrated_files[[i]], sep = "\t")
  print(i/length(input_filenames)*100)
}

# we want to add names to the dataframes so they are used e.g. when writing csvs. 
# first strip everythign after and including _interact .... .tsv
stripped_filenames <- gsub("_interact.*", "", input_filenames)



# assign this to our list
names(calibrated_data) <- stripped_filenames
```

```{r data filtering by PTM}
# source the PTM filtering function
source("scripts/PTM_filtering_fun.R")
# determine what PTMs are of interest to use in function
PTMs_of_interest = c("S[167]", "T[181]", "Y[243]") # here phosphorylation of S, T, and Y


# for every calibrated dataset
filtered_data <- list()
for (i in 1:length(calibrated_data)) {
  #apply the PTM filtering function to only include peptides with phosphtylation
  print(i)
  print(i/length(calibrated_data)*100)
  filtered_data[[i]] <- FilterPTMs(df = calibrated_data[[i]],
                                   PTMs_of_interest = PTMs_of_interest)
}
# once again set the name for each dataset
names(filtered_data) <- stripped_filenames
# then remove the list of read in data to free memory
rm(calibrated_data)
gc()
```

```{r add_peptidoform_id_and_dataset_ID}
source("scripts/Generate_peptidoform_ID_v2.R")
# add peptidoform ID and its scipher + dataset ID to each dataset to enable subsequent filtering
pepcols <-  c("peptide", "mod_peptide") # cols with peptide and PTM data
# these are defaults, here just for ease
peptidoform_id_summaries <- list()

# i = 19
for (i in 1:length(filtered_data)) {
  dataset_ID <- names(filtered_data[i]) 
  print(dataset_ID)
  print(i/length(filtered_data)*100)
  filtered_data[[i]]$dataset_ID <- dataset_ID  # set the dataset ID to its unique folder name
  peptidoform_id_summaries[[i]] <- Generate_Peptidoform_ID(df = filtered_data[[i]],
                                   outname = dataset_ID) # set name for saving .csv files
}

# head(filtered_data[[i]])

# the data has been written... did not return df for some reason, maybe I didn't source the function after changing? anyway...
rm(peptidoform_id_summaries)
rm(filtered_data)
gc()
```


