import os
import sys



def extract_meta_data(inputfile,outprefix):
    cwd = os.getcwd()
    metadata_files = []
    raw_file_spectra_counts = {}
    raw_file_psm_counts = {}

    f = open("mzml_counts.txt","r")

    for line in f:
        line = line.rstrip()
        cells = line.split(":")
        raw_file_spectra_counts[cells[0]] = cells[1]
        #print(cells[0] + "\t" + cells[1])

    #Now read the PSM tsv file
    f_psms = open(inputfile,"r")
    line_counter = 0
    for line in f_psms:
        line = line.rstrip()
        cells = line.split("\t")
        #header row
        if line_counter == 0:
            if cells[0] != "spectrum":
                exit("Expecting first column to have header spectrum, exiting\n") #TODO recognise file headers
        else:
            spectrum = cells[0]
            raw_file_name = spectrum.split(".",1)[0]+".mzML" #150923_KT_YiWa_10-1.00004.00004.2
            psm_count_per_raw_file = 0
            if raw_file_name not in raw_file_spectra_counts:
                print("Didn't recognise raw file name in dictionary, exiting:",raw_file_name)
                exit()
            if raw_file_name in raw_file_psm_counts:
                psm_count_per_raw_file = raw_file_psm_counts[raw_file_name]
            psm_count_per_raw_file +=1
            raw_file_psm_counts[raw_file_name] = psm_count_per_raw_file
        line_counter+=1

    f_out = open(outprefix + "_psm_stats.tsv","w")
    f_out.write("raw_file\tpsm_count\tspectra_count\trecovery\n")
    for raw_file in raw_file_spectra_counts.keys():
        spectra_count = raw_file_spectra_counts[raw_file]
        psm_count = raw_file_psm_counts[raw_file]
        f_out.write(raw_file + "\t" + str(spectra_count) + "\t" + str(psm_count) + "\t" + str(float(psm_count)/float(spectra_count))+"\n")
    f_out.close()

    #for file in raw_file_psm_counts.keys():
    #    print(file,"\t",raw_file_spectra_counts[file])


if len(sys.argv)!= 3:
    print("Exit - expected usage\npython ",  sys.argv[0]," thresholded_psm_file.tsv file_prefix\n"
          "This script is to be run in a folder already containing one mzml_counts file generated by this command grep -src \"MSn spectrum\" *.mzML >> mzml_counts.txt\n"
                                                         ", and the thresholded PSM file in tsv format\n"
                                                         "file_prefix should be PXD code to give file name to write stats to ")
else:
    extract_meta_data(sys.argv[1],sys.argv[2])









